In [2]:
import numpy as np
A=np.array([[0,1,0,0],[12,0,0,4],[0,0,0,1.],[0,-4.,0,0]])
B=np.array([[0,0],[1,0],[0,0],[0,1]])

In [6]:
B1=B[:,0]
B2=B[:,1]

In [11]:
np.dot(A,B1)

array([ 1.,  0.,  0., -4.])

In [15]:
A2=np.dot(A,A)
A3=np.dot(A,A2)
K=np.array([B1,np.dot(A,B1),np.dot(A2,B1),np.dot(A3,B1)])
K

array([[  0.,   1.,   0.,   0.],
       [  1.,   0.,   0.,  -4.],
       [  0.,  -4.,  -4.,   0.],
       [ -4.,   0.,   0.,  16.]])

In [17]:
from numpy.linalg import matrix_rank
matrix_rank(K)

3

In [18]:
K[3,3]
K[3,:]

array([ -4.,   0.,   0.,  16.])

In [34]:
P=np.array([K[0,:], K[1,:], K[2,:],[0,0,0,1]])
P=P.transpose()
P

array([[ 0.,  1.,  0.,  0.],
       [ 1.,  0., -4.,  0.],
       [ 0.,  0., -4.,  0.],
       [ 0., -4.,  0.,  1.]])

In [35]:
from numpy.linalg import inv
Pi=inv(P)
Pi

array([[ 0.  ,  1.  , -1.  ,  0.  ],
       [ 1.  , -0.  , -0.  , -0.  ],
       [-0.  , -0.  , -0.25, -0.  ],
       [ 4.  ,  0.  ,  0.  ,  1.  ]])

In [31]:
np.dot(Pi,P)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [32]:
np.dot(Pi,np.dot(A,P))

array([[ 0.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  , -4.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , -0.25],
       [ 0.  ,  0.  ,  0.  ,  0.  ]])

In [33]:
np.dot(Pi,B1)

array([ 1.,  0.,  0.,  0.])